In [1]:
import gym
import numpy as np

SFFF       (S: starting point, safe)
FHFH       (F: frozen surface, safe)
FFFH       (H: hole, fall to your doom)
HFFG       (G: goal, where the frisbee is located)

Observation Space = 16
Action Space = 4
Reward Range = (-inf, inf)
tStepL = 100
Trials = 100
rThresh = 0.78


In [2]:
env = gym.make('FrozenLake-v0')

In [3]:
x = env.reset()
print(x)

0


In [4]:
#Initialize table with all zeros
Q = np.zeros([env.observation_space.n,env.action_space.n])
# Set learning parameters
lr = .8 #learning rate, alpha
y = .95 #discount factor , gamma
num_episodes = 2000
#create lists to contain total rewards and steps per episode
#jList = []
rList = []
for i in range(num_episodes):
    #Reset environment and get first new observation
    s = env.reset()
    rAll = 0
    done = False
    j = 0
    #The Q-Table learning algorithm
    while j < 99:
        j+=1
        #Choose an action by greedily (with noise) picking from Q table
        a = np.argmax(Q[s,:] + np.random.randn(1,env.action_space.n)*(1./(i+1)))
        #Get new state and reward from environment
        s1,reward,done,_ = env.step(a)
        #Update Q-Table with new knowledge
        Q[s,a] = Q[s,a] + lr*(reward + y*np.max(Q[s1,:]) - Q[s,a])
        rAll += reward
        s = s1
        if done == True:
            break
    #jList.append(j)
    rList.append(rAll)

In [5]:
print ("Score over time: " +  str(sum(rList)/num_episodes))

Score over time: 0.6125


In [6]:
print ("Final Q-Table Values")
print (Q)

Final Q-Table Values
[[2.75901842e-01 1.21039018e-02 8.14552873e-03 1.27054725e-02]
 [8.04461704e-03 1.26426202e-03 4.91438653e-04 2.49435802e-01]
 [1.49941406e-01 4.20927835e-03 7.86874548e-03 0.00000000e+00]
 [7.59968437e-04 0.00000000e+00 0.00000000e+00 1.21843189e-02]
 [4.15683256e-01 1.45704265e-03 1.59345611e-03 6.14573871e-03]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [3.61751286e-03 2.10411731e-04 2.08092771e-05 3.52257191e-04]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [7.23690707e-03 2.82054546e-04 1.32411607e-02 2.90121371e-01]
 [0.00000000e+00 1.74985059e-01 1.14980291e-04 6.03063666e-03]
 [7.47002498e-01 2.06659023e-04 0.00000000e+00 7.50964846e-05]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 7.08206475e-01 0.00000000e+00]
 [0.00000000e+00 9.86463296e-01 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.